import img from "./assets/images/1.jpg.jpg";

const fakeData = [
  {
    id: 1,
    category: "Vegetables",
    title: "Fresh organic villa farm lomon 500gm pack",
    ratings: "4.5",
    oldPrice: 123.25,
    newPrice: 120.25,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. In, iure minus error doloribus saepe natus?",
    brand: "ESTA BETTERU CO",
    flavour: "Vegetarian",
    weight: "200 Grams",
    speciality: "Gluten Free, Sugar Free",
    info: "Egg Free, Allergen-Free",
    items: 1,
    images: [img, img, img, img],
  },
  {
    id: 2,
    category: "Milk",
    title: "Fresh organic villa farm lomon 500gm pack",
    ratings: "4.5",
    oldPrice: 123.25,
    newPrice: 12.25,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. In, iure minus error doloribus saepe natus?",
    brand: "ESTA BETTERU CO",
    flavour: "Vegetarian",
    weight: "200 Grams",
    speciality: "Gluten Free, Sugar Free",
    info: "Egg Free, Allergen-Free",
    items: 1,
    images: [img, img, img, img],
  },
  {
    id: 3,
    category: "Milk",
    title: "Fresh organic villa farm lomon 500gm pack",
    ratings: "4.5",
    oldPrice: 123.25,
    newPrice: 120.25,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. In, iure minus error doloribus saepe natus?",
    brand: "ESTA BETTERU CO",
    flavour: "Vegetarian",
    weight: "200 Grams",
    speciality: "Gluten Free, Sugar Free",
    info: "Egg Free, Allergen-Free",
    items: 1,
    images: [img, img, img, img],
  },
  {
    id: 4,
    category: "Milk",
    title: "Fresh organic villa farm lomon 500gm pack",
    ratings: "4.5",
    oldPrice: 10,
    newPrice: 10,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. In, iure minus error doloribus saepe natus?",
    brand: "ESTA BETTERU CO",
    flavour: "Vegetarian",
    weight: "200 Grams",
    speciality: "Gluten Free, Sugar Free",
    info: "Egg Free, Allergen-Free",
    items: 1,
    images: [img, img, img, img],
  },
  {
    id: 5,
    category: "Vegetables",
    title: "Fresh organic villa farm lomon 500gm pack",
    ratings: "4.5",
    oldPrice: 123.25,
    newPrice: 120.25,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. In, iure minus error doloribus saepe natus?",
    brand: "ESTA BETTERU CO",
    flavour: "Vegetarian",
    weight: "200 Grams",
    speciality: "Gluten Free, Sugar Free",
    info: "Egg Free, Allergen-Free",
    items: 1,
    images: [img, img, img, img],
  },
  {
    id: 7,
    category: "Vegetables",
    title: "Fresh organic villa farm lomon 500gm pack",
    ratings: "4.5",
    oldPrice: 123.25,
    newPrice: 120.25,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. In, iure minus error doloribus saepe natus?",
    brand: "ESTA BETTERU CO",
    flavour: "Vegetarian",
    weight: "200 Grams",
    speciality: "Gluten Free, Sugar Free",
    info: "Egg Free, Allergen-Free",
    items: 1,
    images: [img, img, img, img],
  },
  {
    id: 8,
    category: "Vegetables",
    title: "Fresh organic villa farm lomon 500gm pack",
    ratings: "4.5",
    oldPrice: 123.25,
    newPrice: 120.25,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. In, iure minus error doloribus saepe natus?",
    brand: "ESTA BETTERU CO",
    flavour: "Vegetarian",
    weight: "200 Grams",
    speciality: "Gluten Free, Sugar Free",
    info: "Egg Free, Allergen-Free",
    items: 1,
    images: [img, img, img, img],
  },
];
export default fakeData;
